# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
      
  publish:
    needs: build
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - name: Publish
        run: dotnet publish -c Release -r win-x64 --self-contained true -o ./publish

      - name: Stop Website
        run: |
          Import-Module WebAdministration
          Stop-Website -Name "LoginService"

      - name: Deploy to IIS
        run: |
          Remove-Item -Path "C:\Deployment\LoginService\*" -Recurse -Force -ErrorAction SilentlyContinue
          Copy-Item -Path ".\publish\*" -Destination "C:\Deployment\LoginService" -Recurse -Force
      - name: Start Website
        run: |
          Import-Module WebAdministration
          Start-Website -Name "LoginService"
