# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
  publish:
     needs: build
     runs-on: self-hosted
     steps:
       - name: Publish
         run: dotnet publish -c Release -r win-x64 --self-contained true -o ./publish
       
       - name: Stop IIS AppPool
         run: |
          Import-Module WebAdministration
          Stop-WebAppPool -Name "CyberTIPAppPoll"
          
       - name: Deploy to IIS
         run: |
          Remove-Item -Path "C:\Deployment\LoginService\*" -Recurse -Force -ErrorAction Stop
          Copy-Item -Path ".\publish\*" -Destination "C:\Deployment\LoginService" -Recurse -Force
          
       - name: Start IIS AppPool
         run: |
          Import-Module WebAdministration
          Start-WebAppPool -Name "CyberTIPAppPoll"
